### ISSUE TITLE
Guide for make dlc 

### ISSUE THREAD

**Issue by josediegorobles** [p2pderivatives/rust-dlc#8]
Hi,

There are some guide for make dlcs with rust-dlc? Some example?

Thanks

**Comment by Tibo-lg** [comment]
Hi,

Unfortunately there is no guide or example at the moment. The closest thing are the integration tests: https://github.com/p2pderivatives/rust-dlc/blob/master/dlc/tests/execution_tests.rs (or if you want to see for numerical outcome and multi oracle which is not in master yet: https://github.com/p2pderivatives/rust-dlc/blob/feature/multi-oracle/dlc/tests/execution_tests.rs).

A tutorial + examples will come at some point but tbh it's not a high priority at the moment given that there is still a lot of ground work to do. Happy to answer any question you might have though.

**Comment by josediegorobles** [comment]
Thanks!

I will try (when i'll have some time) to make my way with the integration tests. I'm very interested in the idea.

By the way there are some "good for beginners" issues in the project? I don't know if I will have time but I'm interested in programming for rust and the "bitcoin universe" so if there are something i will give a try.

Thanks again

**Comment by Tibo-lg** [comment]
> I will try (when i'll have some time) to make my way with the integration tests. I'm very interested in the idea.

Cool let me know how it goes, and again feel free to ask questions!

> By the way there are some "good for beginners" issues in the project? I don't know if I will have time but I'm interested in programming for rust and the "bitcoin universe" so if there are something i will give a try.

Not really because things are not really settled yet and moving a lot. Maybe one thing that could be nice is make code for a tutorial.  You could try to replicate this one for example: https://p2pderivatives.github.io/cfd-dlc-js/

**Comment by josediegorobles** [comment]
> Not really because things are not really settled yet and moving a lot. Maybe one thing that could be nice is make code for a tutorial. You could try to replicate this one for example: https://p2pderivatives.github.io/cfd-dlc-js/

Sounds interesting, maybe I will try to replicate the tutorial to try to do my first dlc in rust... if I try I will question about the problems that probably I will have.

Thanks

**Comment by josediegorobles** [comment]
Hi, i've tryed to make something similar to the tutorial basing on integration tests.
But the tests are failing in creating dlc transactions:

---- integration_tests_close stdout ----
thread 'integration_tests_close' panicked at 'Error creating dlc transactions.: InvalidArgument', dlc/tests/execution_tests.rs:187:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::expect
             at /home/jdrobpar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:997:23
   4: execution_tests::integration_tests_common
             at ./tests/execution_tests.rs:178:23
   5: execution_tests::integration_tests_close
             at ./tests/execution_tests.rs:153:5
   6: execution_tests::integration_tests_close::{{closure}}
             at ./tests/execution_tests.rs:152:1
   7: core::ops::function::FnOnce::call_once
             at /home/jdrobpar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by josediegorobles** [comment]
Hi, anyone know how to solve this? Maybe i'm missing something obvious but i'm really interested and i'm stuck

**Comment by Tibo-lg** [comment]
It's difficult to tell exactly what issue you're having, but AFAICT the error you get comes from here: https://github.com/p2pderivatives/rust-dlc/blob/master/dlc/src/lib.rs#L214

Which means that the sum of the outcomes is not always equal to the total collateral. 

If you can share the code you run and how to reproduce your issue it would help.

**Comment by Tibo-lg** [comment]
There is now a sample application on the repository so closing this.
